### PR TITLE
[medReformatViewer] update views with mouse events²

### PR DESCRIPTION
**Pull request by mathildemerle**
From Inria-Asclepios/music#199

"Solves #1 every mouse event (not the 'r' shortcut)"

### CODE REVIEW

**Comment by LoicCadour** [comment]
From my understanding, the problem was : "When scrolling on any view, in Reformat mode, no slicing is done unless you click on the view."
I am afraid it's still the same after this PR.

**Comment by fcollot** [comment]
I reviewed lcadour's test (by looking at his screen) and confirm that it does not work...

**Comment by mathildemerle** [comment]
I tried again, and i needed to compile everything from scratch and it works :)

**Comment by LoicCadour** [comment]
On my mac, nothing happens when you slice, the update is done when you move the mouse.

**Comment by mathildemerle** [comment]
Hehe, i swear it's working on my computer/linux :'). I just start from scratch music/medinria-private and medinria-public again, and this time i've rebased also this branch : when i use the scroll wheel without moving my mouse, the slices are changed ^^.

**Comment by fcollot** [comment]
The problem is we haven't really found what triggers the refresh of the current slice (haven't spent that much time looking though), and whatever event(s) are causing it, they may be handled differently on different OS.

**Comment by mathildemerle** [comment]
I just updated this PR. Is it working on your OS now? :)

**Comment by LoicCadour** [comment]
Unfortunately not ...
If it was working on Linux with your single-lined commit, please rm the second one and we'll merge it, and try to find a solution for Mac

**Comment by mathildemerle** [comment]
Oki, i removed the last commit from this PR (thanks to your method Loic ^^). Yes we can take it as a PR for linux and work in the future to a solution for mac :)

**Pull request merged**
