### PR TITLE
Port over music plugins

### PR DESCRIPTION
**Pull request by mikejbuckingham**
This PR ports over the music plugins that are now considered part of inria's public codebase.

I will send a mail detailing how to get all of this to work, but ultimately it's not too complex.

Something to note - I have created the medUtilities library in medInria. This is to accommodate those elements of musicLibs that were required by these plugins. Rather than port all of musicLibs over, I have just ported those files that were necessary, as I don't know which files in musicLibs must remain private.

Let's discuss this on Monday - please see my mail for more info.

### CODE REVIEW

**Comment by mathildemerle** [comment]
By the way, why don't we use https://github.com/Inria-Asclepios/medinria-superproject ?

**Comment by LoicCadour** [comment]
What happened to the CMakeLists.txt of the plugins?
They are very different from the previous ones, as if they came from a very old version of MUSIC, and they sometimes forget libraries or add useless ones.
I am gonna try to change that.

**Comment by LoicCadour** [comment]
Can you allow me to push on this branch plz?

**Comment by mathildemerle** [comment]
I'm ok for this PR by the way

**Comment by LoicCadour** [comment]
On my side, it compiles on Windows.
Just compiles unfortunately. I have issues with my new VS13 environment.
But I think you can merge it.

**Comment by mathildemerle** [comment]
Flo is ok, i merge !

**Pull request merged**
