### PR TITLE
Right Finder icon

### PR DESCRIPTION
**Pull request by LoicCadour**
Should finally set the right icon in the Finder on all MacOSX versions ... hopefully :'(

### CODE REVIEW

**Comment by mathildemerle** [comment]
I can't test but ok :)

**Comment by fcollot** [comment]
Tested: I've got the proper logo in the Finder, the Activity Monitor and the Launchpad.
Perfect.

**Comment by fcollot** [comment]
(I'm on Mavericks BTW, so I can't speak for newer MacOS versions, but I don't see why it should be any different)

**Comment by LoicCadour** [comment]
I've tested on El Capitan (last one) and Snow Leopard (very old one) and it's one as well.
So I merge.

**Pull request merged**
