### PR TITLE
[qss] disabled buttons more visible

### PR DESCRIPTION
**Pull request by mathildemerle**
As asked, the disabled buttons are more visible.

:m:

### CODE REVIEW

**Comment by LoicCadour** [comment]
It indeed improves distinction between enabled and disabled buttons. Good.
Can we also improve the difference between checked and unchecked buttons (e.g *Closed Polygon* button), for instance by setting the text orange (as it's done with the tabs in Roi Management Tbx).

**Comment by mathildemerle** [comment]
Done, text in orange for pushButton clicked :)

**Comment by LoicCadour** [comment]
Perfect!

**Comment by msermesant** [comment]
OK for me

**Pull request merged**
