### PR TITLE
[export/import] allow to use path with accent

### PR DESCRIPTION
**Pull request by mathildemerle**
Allow to export and import data using path with accents.

:m:

### CODE REVIEW

**Comment by LoicCadour** [comment]
I think you had the same pb with database path, could you include the change as well, please?

**Comment by mathildemerle** [comment]
What do you mean? When we import DICOM?

**Comment by LoicCadour** [comment]
Oh I forgot, it's not merged .....................

**Comment by LoicCadour** [comment]
Fine.

**Pull request merged**
