### PR TITLE
Metadata && msegAlgoPaintToolBox

### PR DESCRIPTION
**Pull request by mathildemerle**
Hello,

This is a part of the cleaning of metadata in the soft. The other part is going to be on MUSIC.

And the msegAlgoPaintToolBox debug which disappeared from loic's medinria and which is very important for user...

### CODE REVIEW

**Comment by LoicCadour** [comment]
Is your branch up-to-date? Doesn't look so.

**Comment by mathildemerle** [comment]
Since you secretly removed one of my accepted-PR, git is lost. Thx.

**Comment by fcollot** [comment]
But removed or not, it should not cause a problem with git if you always pull from the master before pushing your next PR, if I'm not mistaken.

**Comment by mathildemerle** [comment]
I dit a pull rebase on loic's branch :/

**Comment by LoicCadour** [comment]
I think it has been integrated. Can I close it?

**Comment by mathildemerle** [comment]
if it's integrated yes, are you sure about that ? :)

**Comment by LoicCadour** [comment]
You said ok for PR#18 so I thought it was fine.

**Comment by mathildemerle** [comment]
https://github.com/LoicCadour/medInria-public/pull/18 is a very small part of https://github.com/LoicCadour/medInria-public/pull/16 
The 18th is ok, but we need the rest of the code

**Pull request closed without merging**
