### PR TITLE
msegAlgorithmPaintToolBox and medFiltering

### PR DESCRIPTION
**Pull request by mathildemerle**
:imp: 

1° setOutputMetaData >> copyMetaDataFrom
2° remove warnings, i hate warnings >< (:p)
3° problem of multiple importation of data

A small update on medFiltering

ADD : msegAlgorithmPaintToolBox avoiding user crash with buttons without input (Save/Import,etc)

ADD2 : AlgoPaintToolBox: objectName, switch Upper & Lower button, remove warnings, change tlbx name

:dancers: 
Mathilde

### CODE REVIEW

**Comment by mikejbuckingham** [comment]
For the C-style casts : Do we really need to swap between int to unsigned int and then back to int?

It seems to me that a lot of these conversions could be solved if we were to use a consistent type throughout. If we can't have negative values, let's convert everything to unsigned. If we can, everything should be signed.

**Comment by mathildemerle** [comment]
Yes, we can do that. However, it's not my code, so i do not want to do mistakes. And I do not have so much time to spend to that ^^

**Comment by mikejbuckingham** [comment]
Fair enough - in which case I'd suggest we leave it with the warnings, so when somebody does have time to fix it, they can do so properly. Performing C-Style casts to remove the warnings doesn't actually fix the problem the compiler is warning us about - it's just silencing the compiler.

**Comment by LoicCadour** [comment]
This PR should be on LOIC/music

**Comment by mathildemerle** [comment]
Did you change between music_temp and music ? We need to know locations where PR must be done :)

**Comment by LoicCadour** [comment]
It has always been music

**Pull request closed without merging**
