### PR TITLE
MUSIC, new theme ! 

### PR DESCRIPTION
**Pull request by mathildemerle**
:tada: 

New theme for MUSIC \o/ : 

> colors
> main logo, small logo, installer logo
> MUSIC License
> add LIRYC/INRIA new authors

:palm_tree:

### CODE REVIEW

**Comment by mathildemerle** [comment]
You have to add the last commit also :) "license in ut8"

**Comment by LoicCadour** [comment]
it's the one I have commented.
How can I check the right display of the LICENCE?

**Comment by mathildemerle** [comment]
Oh MUSIC -> About -> License :)

**Comment by mathildemerle** [comment]
Can we merge it ? I wanted to work on medInria side and i would like to work on this basis.

**Comment by mathildemerle** [comment]
Merged by the way. If you want me to add something, i will do an other PR :)

**Pull request merged**
