### PR TITLE
[MERGE] debug metadata already in other medinria

### PR DESCRIPTION
**Pull request by mathildemerle**
reverse https://github.com/medInria/medInria-public/commit/b116c8c2995e391e435135fe2d4fd2c8c008e87a

### CODE REVIEW

**Comment by fcollot** [comment]
Looks good to me. Can be merged now I think if Loic is ok.

**Comment by LoicCadour** [comment]
Is it a new thing or something we've lost in the merge?

**Comment by fcollot** [comment]
It's something we had fixed, that was fixed differently in medInria, so it now uses the "medInria way"

**Comment by LoicCadour** [comment]
ok fine

**Pull request merged**
