### PR TITLE
Expiry date and "Research prototype not for clinical use" in the status bar

### PR DESCRIPTION
**Pull request by LoicCadour**
This software will self destruct in one year...

Chrono starts the last time you rebuild medInria (after re-configuration with CMake). 

To acknowledge the users, the expiry date is written in the window title.
screen shot 2015-12-15 at 14 13 14

### CODE REVIEW

**Comment by msermesant** [comment]
ça me refait pense à ce qu'Hakim avait rajouté pour VP2HF : "Research Prototype not for Clinical Use" en rouge dans la barre d'état. Peut etre qu'on devrait le rajouter aussi pour se blinder (meme si c'est dit dans la license)

**Comment by LoicCadour** [comment]
OK, j'essaie de retrouver ça.

**Comment by LoicCadour** [comment]
screen shot 2015-12-15 at 15 17 15

Something like that?

**Comment by msermesant** [comment]
yes, exactly.

**Comment by msermesant** [comment]
(the status bar gets a bit crowded, we should probably clean it at some point)

**Comment by mathildemerle** [comment]
Fine for me :)

**Comment by mathildemerle** [comment]
Please, is it possible de review this PR @mikejbuckingham @fcollot or @msermesant ? Loic needs it to do the DMG that the other teams (Michal, Laura, etc) are waiting  since few weeks. Laura do not have any DMG, she can't work, and Michal has the wrong DMG that Hubert had also.
Thx by advance.

**Comment by fcollot** [comment]
good to go

**Comment by msermesant** [comment]
sorry to be late (I was busy this morning) but it seems that changing the name of the executable is creating problems (regarding database when updating,...) so maybe we should rather write the expiration date somewhere else (home workspace?)

**Comment by mathildemerle** [comment]
Well, if you want, no problem :)

**Pull request merged**
