### PR TITLE
View Settings - toolbox less huge

### PR DESCRIPTION
**Pull request by mathildemerle**
:yellow_heart: 

I began to remove some useless spaces in View Settings. 

Lines 393/394 from medAbstractView.cpp... do anyone know if it's used sometimes ? It's usually empty and does blank spaces.  

:yellow_heart:

### CODE REVIEW

**Comment by msermesant** [comment]
good, I was trying to remove these as well (unsuccessfully...)

**Comment by mathildemerle** [comment]
There is no doc for this, so it was complicated also for me :). We could do better for these toolbox, but i did not find the exact location of the creation of the 4 logos (orientations). Maybe later if i find, i could try something else.

**Comment by mathildemerle** [comment]
No review for this one for the moment please. I found a problem with the 3D mode (which display a new small window with 3d parameters instead of displaying it in the toolbox).

**Comment by mathildemerle** [comment]
Done, you can review. There are some weirds things on the 3D-orientation side, but it was there before.

**Comment by fcollot** [comment]
ok for me

**Comment by mikejbuckingham** [comment]
me too!

**Pull request merged**
