### PR TITLE
[FilteringSelectorTbx] Adds selection of itkFilters through its identifi...

### PR DESCRIPTION
**Pull request by LoicCadour**
...er and removes a condition that forces the input to belong to the db (a pain when doing pipelines)

Might be good if integrated in medInria.

### CODE REVIEW

**Comment by LoicCadour** [comment]
Actually "[FilteringSel..] ..." and "[itkFilter] ..." can be integrated to medinria I guess.

**Comment by mikejbuckingham** [comment]
const reference for the QString argument please! :P

**Comment by fcollot** [comment]
While I agree that const and references should be used when possible, I believe QT objects like QString don't need either due to QT's implicit sharing mechanism (http://qt-project.org/doc/qt-4.8/implicit-sharing.html).

**Comment by mikejbuckingham** [comment]
@fcollot Interesting, I wasn't aware that this was a characteristic of Qt Objects. Ultimately we're doing the same thing by using a const reference here, but preventing the callee from having a hidden duplication. 

I honestly don't think there's much in it, but as general practice I suggest we use const ref unless we explicitly want the behaviour of copy-on-write (as it makes debugging a pain)

**Comment by fcollot** [comment]
Ok fine with me as it is idiosyncratic with string arguments anyways.

**Comment by fcollot** [comment]
...and I meant Idiomatic. That should teach me not to use complex words...

**Pull request merged**
